"""add intpk and cascade delete posts to delete user

Revision ID: 9b202c68bf20
Revises: a710da1514cd
Create Date: 2025-11-11 00:51:30.457426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b202c68bf20"
down_revision: Union[str, Sequence[str], None] = "a710da1514cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("posts_author_id_fkey"), "posts", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "posts", "users", ["author_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.create_foreign_key(
        op.f("posts_author_id_fkey"), "posts", "users", ["author_id"], ["id"]
    )
    # ### end Alembic commands ###
